### ISSUE TITLE
Running Discum in a thread alongside flask

### ISSUE THREAD

**Issue by Pitu7944** [Merubokkusu/Discord-S.C.U.M#104]
Hello i want to use discum to listen for my api requests and then send a message with the request body to a channel. Converting the bot to a class did not work for me.

**Comment by AeroActuallyDev** [comment]
why dont you just use webhooks with aiohttp instead?

**Comment by Pitu7944** [comment]
im not experienced enough to risk getting the account banned by some dumb mistake
______________
arandomnewaccount:
it'd actually be safer to use webhooks btw

**Comment by Pitu7944** [comment]
how would i do that? im not that experienced...

**Comment by Pitu7944** [comment]
> arandomnewaccount:
> it'd actually be safer to use webhooks btw

i cant use webhooks because its not my server tho
____________
arandomewaccount:
alr ok so, since discum separates rest apis from gateway apis and sending a message is a rest api interaction, all you have to do (after initializing the discum bot), is bot.sendMessage(...). See the docs for a list of the arguments for sendMessage.

closing this as it's a question on how to use the lib. I'd rather have these issues be related to bugs or related in discum. 
Btw, discum's a synchronous lib. If you're looking for an asynchronous selfbot/userbot lib, I'd suggest [dolfies's d.py](https://github.com/dolfies/discord.py-self)
