### ISSUE TITLE
_MEI383322\\random_user_agent/user_agents.zip file not found

### ISSUE THREAD

**Issue by bennyscripts** [Merubokkusu/Discord-S.C.U.M#115]
im currently using Discum in my selfbot for fetching members, when ever i use the fetch member command i get an error telling me that "_MEI383322\\random_user_agent/user_agents.zip" was not found.

![](http://hypixel.lol/raw/23IVmDej.png)

Anyway i can fix this?
__________
arandomnewaccount:
that's an issue for random_user_agent: https://github.com/Luqman-Ud-Din/random_user_agent

alternatively, if you dont care about generating random user agents, you can just set the user agent when you initialize the client: https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/Get_Started.md#initializing-your-client

**Comment by marcos10pc** [comment]
wait....
