### ISSUE TITLE
Limited using multibot

### ISSUE THREAD

**Issue by PetruIulian** [Merubokkusu/Discord-S.C.U.M#119]
Hi, im trying to login in over 10k tokens, but the bot connects only to 300 and then they log out, if i try to login to 100 tokens, they will stay alive, but with bigger amount they will not connect and the one that connected will disconnect, any idea why?
_________________________
arandomnewaccount:
do any errors pop up? What are the close codes and reasons of the bots that log out?

**Comment by PetruIulian** [comment]
no errors, they just logging of, maybe there are limitations to open websockets or requests?
in cosole says "creating websocket" or something like that, if there a limit for how many websockets u can create?
_____________________
arandomnewaccount:
probs. I'll try later today with some tokens.

**Comment by PetruIulian** [comment]
and? u figured out something?
_____________
arandomnewaccount: gotta run some more tests when I get some time

edit: try using the dev branch, it's got updates to reduce ram quite a bit (which might fix some of your issues on multibotting):
```
python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git@development#egg=discum
```

**Comment by solidstatecodes** [comment]
> no errors, they just logging of, maybe there are limitations to open websockets or requests?
> in cosole says "creating websocket" or something like that, if there a limit for how many websockets u can create?
> 
> arandomnewaccount:
> probs. I'll try later today with some tokens.

Not really unexpected behavior in my opinion. I am 99.999% sure that Discord puts limits on how many concurrent websocket connections and API requests can be made from one IP address - this is standard business practice to stop things like DoS attacks. A normal human would not "log in" as 10000 users.

Either that, or the processing power of your computer and the bandwidth of your network is stopping you. If you want to open 10000 concurrent connections with data constantly streaming in and out of every one of them you would need a powerful server and a **very** good internet connection.

**Comment by grx7** [comment]
@solidstatecodes Any idea why am I getting this error?

Traceback (most recent call last):
  File "bots/DM/discord_text_spam_dm.py", line 11, in <module>
    import discum
ModuleNotFoundError: No module named 'discum'
Traceback (most recent call last):
  File "bots/DM/discord_text_spam_dm.py", line 11, in <module>
    import discum
ModuleNotFoundError: No module named 'discum'

This happen when calling : python3 start.py
_____________
arandomnewaccount:
pls stay on topic or create a new issue. Also, read the docs before posting stuff
