### ISSUE TITLE
how to use events

### ISSUE THREAD

**Issue by bennyscripts** [Merubokkusu/Discord-S.C.U.M#123]
i was looking at the src code for the events in the gateway, how do i use them?
for an example how can i use the on_message event?
_________
arandomnewaccount:
```python
@bot.gateway.command
def test(resp):
    if resp.event.message:
        rawevent = resp.raw
        parsedevent = resp.parsed.auto()
```

theres also an example on the readme

**Comment by bennyscripts** [comment]
thanks

**Comment by bennyscripts** [comment]
how can i mix this with discord py?

**Comment by ghost** [comment]
since discum is sync, it shouldn't be possible to to run discord py and discum at the same time, at least it isn't easy

**Comment by bennyscripts** [comment]
okay, fair
