### ISSUE TITLE
Phone Number

### ISSUE THREAD

**Issue by Vinyzu** [Merubokkusu/Discord-S.C.U.M#124]
Yo, i just wondered if it is possible to put a phone number on the account using discum, because i didnt found anything like that in the docs...
________
arandomnewaccount:
that hasn't been implemented yet. If you want you can make a pull request

**Comment by Vinyzu** [comment]
Mh ill see if i can get a solution!

**Comment by Vinyzu** [comment]
I just noticed id have a fxkin idea on how to do it lolololol
Can u do it or send me how to do it??? Hahaha
_________
arandomnewaccount:
yea ill add it when I get some time. I'm kinda busy until Friday so I'll prob add it over the weekend

**Comment by Vinyzu** [comment]
That would be lit!

**Comment by Vinyzu** [comment]
Is it alr added? :D

**Comment by sudo-do** [comment]
> I just noticed id have a fxkin idea on how to do it lolololol
> Can u do it or send me how to do it??? Hahaha

**api url** https://discord.com/api/v9/users/@me/phone
**header** ```{"phone":"+18052034550"}```

if response is 204, verification SMS is sent so continue the process

**api url** https://discord.com/api/v9/phone-verifications/verify
**header** {"phone":"+18052034550","code":"444444"}

**Comment by sudo-do** [comment]
maybe i can do this, i'll give it a try, I have to learn the structure of discum anyway and this issue may lead it idk

**Comment by ghost** [comment]
waiting review lol
_____________
arandomnewaccount:
thx for making the pr. looking over it rn

Merged pull request. I'll be making some more edits and will update this comment once the setPhone method finalized.

Btw what data is returned from the validate-phone request (I've run out of phone numbers lol). 
Is there a "token" key?

**Comment by ghost** [comment]
> Btw what data is returned from the validate-phone request

nothing important

**Comment by Vinyzu** [comment]
Btw is this also working if the account is phone locked?

**Comment by ghost** [comment]
should work
________
arandomnewaccount:
closing as answered. Basically you'd just set the phone first, wait for a code to arrive, and then validate the phone.
