### ISSUE TITLE
how to parse first N member on guild by online status, for example?

### ISSUE THREAD

**Issue by lionead** [Merubokkusu/Discord-S.C.U.M#134]
when im trying to fetchmembers by example im getting only 400-500 out of 6k members, but i can't even filter them and that's quite problem

**Comment by ghost** [comment]
See [fetchMembers](https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/Gateway_Actions.md#parameters-7)

Example Code to retrieve their username : 
```py
import discum
token = "YOUR_USER_TOKEN"
bot = discum.Client(token= token, log=True)
guild_id = 'THE_GUILD_ID'
channel_id = 'THE_CHANNEL_ID'
bot.gateway.fetchMembers(guild_id, channel_id, keep=['username'], method='overlap',wait=1) #as shown in the docs method=overlap can fetch more member but the speed is decreased
@bot.gateway.command
def memberTest(resp):
    if bot.gateway.finishedMemberFetching(guild_id):
        lenmembersfetched = len(bot.gateway.session.guild(guild_id).members)
        print(str(lenmembersfetched)+' members fetched')
        bot.gateway.removeCommand(memberTest)
        bot.gateway.close()

bot.gateway.run()


for memberID in bot.gateway.session.guild(guild_id).members:
    print(bot.gateway.session.guild(guild_id).members[memberID]['username'])
```

**Comment by lionead** [comment]
> See [fetchMembers](https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/Gateway_Actions.md#parameters-7)
> 
> Example Code to retrieve their username :
> 
> ```python
> import discum
> token = "YOUR_USER_TOKEN"
> bot = discum.Client(token= token, log=True)
> guild_id = 'THE_GUILD_ID'
> channel_id = 'THE_CHANNEL_ID'
> bot.gateway.fetchMembers(guild_id, channel_id, keep=['username'], method='overlap',wait=1) #as shown in the docs method=overlap can fetch more member but the speed is decreased
> @bot.gateway.command
> def memberTest(resp):
>     if bot.gateway.finishedMemberFetching(guild_id):
>         lenmembersfetched = len(bot.gateway.session.guild(guild_id).members)
>         print(str(lenmembersfetched)+' members fetched')
>         bot.gateway.removeCommand(memberTest)
>         bot.gateway.close()
> 
> bot.gateway.run()
> 
> 
> for memberID in bot.gateway.session.guild(guild_id).members:
>     print(bot.gateway.session.guild(guild_id).members[memberID]['username'])
> ```

it doesn't let me fetch all members on 8k member guild

**Comment by lionead** [comment]
oh, i see, sorry, it only fetches online members. thank you!
