### ISSUE TITLE
How to get information from deleted messages

### ISSUE THREAD

**Issue by JuniorSuperTux** [Merubokkusu/Discord-S.C.U.M#139]
I'm just wondering if there's any way for me to get information from deleted messages, such as author ID and name, message ID and content, channel ID, and stuff?

**Comment by JuniorSuperTux** [comment]
I didn't wrote the title and content too well. By getting information from the deleted message, I actually mean when the "message delete" event occurs, is there anyway I can get information from the message that's getting deleted?
__________________
arandomnewaccount:
all the events: https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/events.md
just use them like so:
```python
@bot.gateway.command
def test(resp):
    if resp.event.message_deleted:
        data = resp.parsed.auto() #type dictionary
        ...

bot.gateway.run()
```

**Comment by ghost** [comment]
Which Information do you want, ID of the message, Content ?

**Comment by JuniorSuperTux** [comment]
Yes, content, author's user ID, and channel ID. I've tried that, but I just couldn't find the correct key for the dictionary.
_________
arandomnewaccount:
ah turns out discord only sends back the channel_id, guild_id (if applicable), and id in MESSAGE_DELETE events.

bot.getMessage doesn't work right for deleted messages (it just sends back the closest [visible] message to the deleted message). So...ig you'd have to archive the last 15-20 messages and if a message_delete comes in for one of those messages, log that.

edit: closing this as answered.
