### ISSUE TITLE
need help - get servers + get channels

### ISSUE THREAD

**Issue by ghost** [Merubokkusu/Discord-S.C.U.M#141]
as i'm doing a gui for my bot i need to
get list of servers user in
get channels of a server

can you pls write an example code for me plsxx

**Comment by sudo-do** [comment]
#print all servers user in
    print(client.gateway.user.guilds)
    #print all channels in a server
    print(client.gateway.user.guilds[0].channels)

**Comment by Svenskithesource** [comment]
Just learn how to read documentation
_________
arandomnewaccount:
yes. this. 5 min tops in docs (use ctrl-f)

**Comment by ghost** [comment]
or write a readable documentation
______________
arandomnewaccount:
maybe make a pr to the docs or add an example here for what would be more readable?

the docs are currently organized by how the api is organized + how discum's code is organized

also, instead of bot.getGuilds (rest api), you might want to use bot.gateway.session (if you're connecting to the gateway). That has a lot of data:
https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/General.md#botgatewaysession
