### ISSUE TITLE
example of proxy usage?

### ISSUE THREAD

**Issue by lionead** [Merubokkusu/Discord-S.C.U.M#147]
every time i try using proxies i get different errors, don't find working example of using proxies

**Comment by lionead** [comment]
found a solution!
the all you need to do is `pip install urllib3==1.25.11`
https://stackoverflow.com/questions/66642705/why-requests-raise-this-exception-check-hostname-requires-server-hostname

**Comment by lionead** [comment]
@Merubokkusu add this dependency please

**Comment by cth-latest** [comment]
Requests module already implement proxies support. Do not need urllib3

**Comment by lionead** [comment]
> Requests module already implement proxies support. Do not need urllib3

try putting proxy yourself, it won't work
urllib is part of requests, and it doesn't support proxy format which discum is currently using
