### ISSUE TITLE
Phone Number Docs Error?

### ISSUE THREAD

**Issue by Vinyzu** [Merubokkusu/Discord-S.C.U.M#159]
So in this doc:
https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/REST_Actions.md#setphone
(and)
https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/REST_Actions.md#validatephone

It says you have to do:
```
bot.setPhone("+12222222222")
and
bot.validatePhone("+12222222222", "123456")
```
but ive coded the function and what ive got you would have to do:
```
temp = bot.setphone("+12222222222")
temp.validate("123456")
```
due to the code beeing this:
https://github.com/sudo-do/Discord-S.C.U.M/blob/90d4c5b2c3073355c221e0d10073b7f260db0790/discum/user/user.py#L179
______________
arandomnewaccount:
that's sudo-do's discum fork. The docs on this repo refer to the code on this repo. 
If you use a fork, then the usage might be different.

https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/discum/user/user.py#L180

**Comment by Vinyzu** [comment]
Ok, thanks!

**Comment by ghost** [comment]
Yep, he edited it idk why lol
