### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'getRecentMessage'

### ISSUE THREAD

**Issue by CUPZYY** [Merubokkusu/Discord-S.C.U.M#2]
Hi,
When i try to write bot.getRecentMessage(*ChannelID*, num=1)
I get this: "AttributeError: 'Client' object has no attribute 'getRecentMessage'"
Please help

Best Regards
Cupzyy

**Comment by SquarishRectangle** [comment]
I also got this issue even after reinstalling and updating. Anyone know what might be going on?
