### ISSUE TITLE
ID's problem

### ISSUE THREAD

**Issue by PAWELE16** [Merubokkusu/Discord-S.C.U.M#218]
How to make the IDs automatically save in the txt file? I did as the author shows in the youtube video and it doesn't work and now I don't know how to do it. And I could use it on large servers.

**Comment by ghost** [comment]
```python
f = open('users.txt', "a")
for memberID in members:
     print(memberID)
     f.write(memberID = '\n')
f.close()
```

**Comment by PAWELE16** [comment]
> ```python
> f = open('users.txt', "a")
> for memberID in members:
>      print(memberID)
>      f.write(memberID = '\n')
> f.close()
> ```

Not working for me :( 
Any ideas?
________
arandomnewaccount:
1) you leaked your token
2) this should work:
```python
with open('users.txt', 'a+') as f:
    for memberID in members:
        f.write(memberID + '\n')
```
if it doesn't work then maybe the fetched members got cleared somehow? You can check how many members the program fetched by doing `len(members)`
