### ISSUE TITLE
gettingGuildMembers.py

### ISSUE THREAD

**Issue by l29** [Merubokkusu/Discord-S.C.U.M#235]
Hi,
It only scrapes the online user. Would it possible to scrape all Member (offline and online) ?

**Comment by wtfismyname69420** [comment]
The documentation for this is found [here](https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/fetchingGuildMembers.md#search-for-members-by-query)

While it may not scrape **ALL** users, it's pretty close enough in my opinion.

Please read the documentation before posting an issue.
_____________
arandomnewaccount:
yep. Also, @v6r, if you read the docs you'll see that there're ways to try and scrape some offline members too
