### ISSUE TITLE
joinGuild not working correctly and code developement.

### ISSUE THREAD

**Issue by hexlocation** [Merubokkusu/Discord-S.C.U.M#261]
1. joinGuild isnt working anymore
2. Is this project still worked on or is it dead.
_______________
arandomnewaccount:
1. if you're getting 400 bad request, then this issue is a duplicate of https://github.com/Merubokkusu/Discord-S.C.U.M/issues/206. Captcha solving hasn't been added to discum yet. Try using a better proxy maybe?
2. still being worked on, check commit history

**Comment by wtfismyname69420** [comment]
lol "Is this project still worked on or is it dead."
![image](https://user-images.githubusercontent.com/84185962/146119031-848ba787-5974-4f08-833d-ab0e2f288ac4.png)
