### ISSUE TITLE
Error while scraping members in a guild

### ISSUE THREAD

**Issue by AshtonBenson** [Merubokkusu/Discord-S.C.U.M#269]
Code was working a few days ago but stopped working. Token loads the info, but then connection drops and the error is thrown up.

Error: lambda () takes 1 positional argument but 3 were given discum
___________
arandomnewaccount:
I've seen others who've gotten the same error from not having the correct discum and websocket_client version.
You can do this as a quick fix (uninstall current version and install correct version):
```python
pip3 uninstall websocket_client
pip3 uninstall discum

pip3 install websocket_client==0.59.0
pip3 install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum
```

**Comment by AshtonBenson** [comment]
Did the fix but now the code doesn't seem to run the discum part, it just blanks in console.
_______
arandomnewaccount:
wdym blanks in console?
could you provide a ss + what code you're trying to run so I could reproduce the error?

**Comment by AshtonBenson** [comment]
Update: It is a little bit fixed, now its not giving me the lambda but now output is
—
Connected to websocket.
←[94m> {'op': 2, 'd': {'token': 'haha', 'capabilities': 61, 'properties': {'os': 'Android', 'browser': 'Chrome', 'device': '', 'browser_user_agent': 'Mozilla/5.0 (Linux; Android 4.1.2; GT-N8010 Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.122 Safari/537.36', 'browser_version': '35.0.1916', 'os_version': '4.1.2', 'referrer': '', 'referring_domain': '', 'referrer_current': '', 'referring_domain_current': '', 'release_channel': 'stable', 'client_build_number': 10892, 'client_event_source': None}, 'presence': {'status': 'online', 'since': 0, 'activities': [], 'afk': False}, 'compress': False, 'client_state': {'guild_hashes': {}, 'highest_last_message_id': '0', 'read_state_version': 0, 'user_guild_settings_version': -1}}}←[m
←[92m< {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-main-ppht",{"micros":0.0}]']}}←[m
entering heartbeat
websocket closed
Connection Dropped. Retrying in 10 seconds.

**Comment by GenaAiv** [comment]
> Update: It is a little bit fixed, now its not giving me the lambda but now output is — Connected to websocket. ←[94m> {'op': 2, 'd': {'token': 'haha', 'capabilities': 61, 'properties': {'os': 'Android', 'browser': 'Chrome', 'device': '', 'browser_user_agent': 'Mozilla/5.0 (Linux; Android 4.1.2; GT-N8010 Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.122 Safari/537.36', 'browser_version': '35.0.1916', 'os_version': '4.1.2', 'referrer': '', 'referring_domain': '', 'referrer_current': '', 'referring_domain_current': '', 'release_channel': 'stable', 'client_build_number': 10892, 'client_event_source': None}, 'presence': {'status': 'online', 'since': 0, 'activities': [], 'afk': False}, 'compress': False, 'client_state': {'guild_hashes': {}, 'highest_last_message_id': '0', 'read_state_version': 0, 'user_guild_settings_version': -1}}}←[m ←[92m< {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-main-ppht",{"micros":0.0}]']}}←[m entering heartbeat websocket closed Connection Dropped. Retrying in 10 seconds.

I got the same issue. Can anyone help?

**Comment by hoemotion** [comment]
> > Update: It is a little bit fixed, now its not giving me the lambda but now output is — Connected to websocket. ←[94m> {'op': 2, 'd': {'token': 'haha', 'capabilities': 61, 'properties': {'os': 'Android', 'browser': 'Chrome', 'device': '', 'browser_user_agent': 'Mozilla/5.0 (Linux; Android 4.1.2; GT-N8010 Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.122 Safari/537.36', 'browser_version': '35.0.1916', 'os_version': '4.1.2', 'referrer': '', 'referring_domain': '', 'referrer_current': '', 'referring_domain_current': '', 'release_channel': 'stable', 'client_build_number': 10892, 'client_event_source': None}, 'presence': {'status': 'online', 'since': 0, 'activities': [], 'afk': False}, 'compress': False, 'client_state': {'guild_hashes': {}, 'highest_last_message_id': '0', 'read_state_version': 0, 'user_guild_settings_version': -1}}}←[m ←[92m< {'t': None, 's': None, 'op': 10, 'd': {'heartbeat_interval': 41250, '_trace': ['["gateway-prd-main-ppht",{"micros":0.0}]']}}←[m entering heartbeat websocket closed Connection Dropped. Retrying in 10 seconds.
> 
> I got the same issue. Can anyone help?

Your discum is outdated tho, if its on the latest try rerunning again and again

**Comment by AshtonBenson** [comment]
Updating discum not using pip gets rid of the update but now back to the original error of no output.
—
target_guildinv = input('Target guild invite (ONLY EVERTHING AFTER discord.gg/)?: ')
target_guildid = input('Target guild id?: ')
target_channelid = input('Target channel id?: ')
headers1 = headers

r = requests.post(f"https://discord.com/api/v9/invites/{target_guildinv}",headers=headers1)
print(r)

guild_id = target_guildid

def close_after_fetching(resp, guild_id):
	if bot.gateway.finishedMemberFetching(guild_id):
		bot.gateway.removeCommand({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
		bot.gateway.close()

def get_members(guild_id, channel_id):
	bot.gateway.fetchMembers(guild_id, channel_id, keep="all", wait=1) #get all user attributes, wait 1 second between requests
	bot.gateway.command({'function': close_after_fetching, 'params': {'guild_id': guild_id}})
	bot.gateway.run()
	bot.gateway.resetSession() #saves 10 seconds when gateway is run again
	return bot.gateway.session.guild(guild_id).members

print("Freezing check")

members = get_members(f'{target_guildid}', f'{target_channelid}') #yes, the channel_id input is required

print("Freezing check #2")
—

and output is just

<Response [200]>
Freezing check
