### ISSUE TITLE
stupid question, but how do  i remove this green text

### ISSUE THREAD

**Issue by Errorcrafter** [Merubokkusu/Discord-S.C.U.M#272]
![image](https://user-images.githubusercontent.com/69189354/146678840-00d43a25-5961-4782-a1d6-f0feb350a670.png)

it still remains even after setting `bot.log` to `{"console":False, "file":"log.txt"}`.
_________
arandomnewaccount:
you're using the incorrect discum version. Uninstall discum and reinstall using:
```
pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum
```

**Comment by Errorcrafter** [comment]
ok its still there

**Comment by ghost** [comment]
> ok its still there

Can you run:
```
pip show discum
```
and send the output here

**Comment by Errorcrafter** [comment]
> > ok its still there
> 
> Can you run:
> 
> ```
> pip show discum
> ```
> 
> and send the output here

![image](https://user-images.githubusercontent.com/69189354/146766297-dc0090f2-6a21-41ca-a0db-66ae25d3b1c0.png)
___________
arandomnewaccount:
are you sure you're using the same python version to run your script & to install?
(maybe installed discum==1.4.0 in py3.7 and ran the script in py3.9 or something like that)

**Comment by Errorcrafter** [comment]
nevermind, it suddenly went away again
