### ISSUE TITLE
Cant add Phone Number

### ISSUE THREAD

**Issue by Vinyzu** [Merubokkusu/Discord-S.C.U.M#274]
Hello ;:D
I wanted to add a phone number via the the .setPhone function, but i got a error which said "You need to update your app to verify your phone number." (Btw i tried it afterwards with manual requests and it gives the same error) U know why it gives me that?
__________
arandomnewaccount:
idk, I can try on my end a bit and get back later

**Comment by Vinyzu** [comment]
ok, thanks ;:D

**Comment by Vinyzu** [comment]
btw i have the supposition that it is bcs of the useragent with which the acc is created
_______________
arandomnewaccount:
hm. What user agent is your discum client using?
You can check this by doing `print(bot._Client__user_agent)`

**Comment by Vinyzu** [comment]
Mozilla/5.0 (Linux; Android 4.1.2; SGH-T999N Build/JZO54K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.92 Mobile Safari/537.36
this one idk why
____________
arandomnewaccount:
hm. ok, it should be fine. I'll get a phone num rq and try to test the reqs on my end

**Comment by Vinyzu** [comment]
Ok thx ;:F
____________
arandomnewaccount:
might not get to testing it today bc a bit busy, will try to test it tmr if I dont today

**Comment by Vinyzu** [comment]
Ok :/
_______
arandomnewaccount:
looks like it needs captcha, which isn't supported by discum yet
the "You need to update your app" part tho seems to be an issue discord needs to fix

**Comment by Vinyzu** [comment]
OK, so i just have to wait for discord to fixx that?
________
arandomnewaccount:
I think discum just needs some captcha-solving support. Either built-in or have some sort of a way to add on a captcha solver

**Comment by Vinyzu** [comment]
If you want me to add smthng like that, i already have code supporting 2captcha capmonster and i thunk anticaptcha

**Comment by BrokedTV** [comment]
> If you want me to add smthng like that, i already have code supporting 2captcha capmonster and i thunk anticaptcha

that would be very nice

**Comment by OrionCodeDev** [comment]
> If you want me to add smthng like that, i already have code supporting 2captcha capmonster and i thunk anticaptcha

+1 maybe do a pull request for it
