### ISSUE TITLE
Suggestion (enhancement): get hidden channels

### ISSUE THREAD

**Issue by ghost** [Merubokkusu/Discord-S.C.U.M#284]
We have `bot.gateway.findVisibleChannels('guildID00000000000')`, so why not make a command for fetching hidden channels?
________
arandomnewaccount:
hmm. I can make a general command for fetching channels with certain inputted permissions. kinda busy rn, will try to add sometime this week

nvm was busy, didn't prioritize cause I cant really think of a good use case for that. If you have a use case for this type of thing let me know and I'll consider

**Comment by Disconsolance** [comment]
You can use `bot.getGuildChannels('guildID00000000000')` and compare it to the output of `bot.gateway.findVisibleChannels('guildID00000000000')` to find out what channels are hidden.

**Comment by ghost** [comment]
that's good enough for me lol
