### ISSUE TITLE
How to differentiate text channels from voice channels

### ISSUE THREAD

**Issue by Bibbors** [Merubokkusu/Discord-S.C.U.M#291]
I have been testing this flood bot that collects all channels IDs and send messages them. I'm stuck in this problem where it tries to message voice channels. Completely messes the efficiency.
Is there a way to differentiate the type of the channels in the code?

**Comment by captain-majid** [comment]
```py
visTextChannels = bot.gateway.findVisibleChannels(guild_id, 'guild_text')
```
