### ISSUE TITLE
adding git

### ISSUE THREAD

**Issue by Noshi123456** [Merubokkusu/Discord-S.C.U.M#292]
writing py -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum leads me into getting 2 errors : ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH
any fix?

**Comment by jewelmuralee** [comment]
You'll need git (https://git-scm.com/downloads)
