### ISSUE TITLE
I get weird return values when using bot.createDM()

### ISSUE THREAD

**Issue by Sun870905** [Merubokkusu/Discord-S.C.U.M#296]
I run the following code.

> try:
  bot = discum.Client(token=token, build_num=0, x_fingerprint='test')
  new_user = bot.createDM([member_id]).json()
except:
  pass

Then I got the following error.
> [+] (<discum.messages.messages.Messages->createDMraw) Post -> https://discord.com/api/v9/users/@me/channels
 [+] (<discum.messages.messages.Messages->createDMraw) {"recipients": ["528324873513205761"]}
 [+] (<discum.messages.messages.Messages->createDMraw) Response < b'\x03p\x00\x00\xef\xbf\xbd\xca\xb9\xef\xbf\xbd\xef \xbf\xbdY\x1d\xef\xbf\xbdK\xef\xbf\xbd\xef\xbf\xbd\x1b\xef\xbf\xbdm\x1f\x00a\x03N\x00"O\x07\xef\xbf\xbd\x05\x16\x186\xef\xbf\xbd\x12+\xef\xbf\xbd\x1f\x7f\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x12\xef\xbf\xbd+\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdr\xef\xbf\xbd\xef\xbf\xbdY\xef\xbf\xbd\xef\xbf\xbdC\x10n\xef\xbf\xbd\xef\xbf\xbd\x1c\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdmr\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\t\xef\xbf\xbd\xef\xbf\xbd^Qi\xef\xbf\xbd,\xef\xbf\xbdc\xef\xbf\xbd\x02g\x1f\xef\xbf\xbdw&\xef\xbf\xbddy\xef\xbf\xbd_\xef\xbf\xbdC\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\x12\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdv\xef\xbf\xbd]W\x10\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xdc\x9a\x0b*\xef\xbf\xbd\xef\xbf\xbd\xd0\x98\xef\xbf\xbd\r\xef\xbf\xbd\xef\xbf\xbdx\xef\xbf\xbd\xef\xbf\xbd;\xef\xbf\xbd\x16\xef\xbf\xbdF.\x1c\xe6\xa9\x83\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xde\xaf\x0f\xef\xbf\xbd\xef\xbf\xbdxA%\xef\xbf\xbd\xef\xbf\xbd=\x04\xef\xbf\xbdtow\xef\xbf\xbdn\xef\xbf\xbd\xef\xbf\xbd5\xef\xbf\xbd+*\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbdo\x00\x03'

How can I get the correct response?

**Comment by dolfies** [comment]
Looks like you need to install brotlipy.
_________
arandomnewaccount:
brotli needs to be installed: https://github.com/google/brotli
