### ISSUE TITLE
Can we add delete_after for sendMessage() ?

### ISSUE THREAD

**Issue by captain-majid** [Merubokkusu/Discord-S.C.U.M#297]
This attribute exists [here](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=context%20send#discord.ext.commands.Context.send), so I wonder if it can be added to [sendMessage()](https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/discum/messages/messages.py#L101) ?

**Comment by dolfies** [comment]
This wouldn't work very well in a sync context.
