### ISSUE TITLE
Cannot install discum[ra]

### ISSUE THREAD

**Issue by r-hou** [Merubokkusu/Discord-S.C.U.M#310]
I tried the command to install it
```python
python -m pip install --user --upgrade -e git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum[ra]
```
but pip reports 
```python
no matches found: git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum[ra]
```
what should I do to install it, thanks!

**Comment by ya-ushel** [comment]
i also getting this error, anybody knows something related to this issue?
_______
arandomnewaccount:
hm it works for me. What python version are you using? Also, do you have git installed (https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)? 

Alternatively, you can just install pycryptodome, pyqrcode, and pypng, as specified here: https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/setup.py#L37
