### ISSUE TITLE
How do i get embeds description?

### ISSUE THREAD

**Issue by ahihiyou20** [Merubokkusu/Discord-S.C.U.M#322]
I tried to get embeds description, I thought it just like get message content. But NOPE, there is a dict (or json data) in a list and I don't know how to get the dict data( or json ). So how do I get that data (embeds,description)?

**Comment by yfantro** [comment]
bro i have no idea how to run the token gen can you please help ?

**Comment by r1n0x** [comment]
> I tried to get embeds description, I thought it just like get message content. But NOPE, there is a dict (or json data) in a list and I don't know how to get the dict data( or json ). So how do I get that data (embeds,description)?

m['embeds']['description'], before make sure it is one

**Comment by ahihiyou20** [comment]
> 

Alr ty you so much bro it worked!!
