### ISSUE TITLE
"Invalid Form Body" error when clicking button.

### ISSUE THREAD

**Issue by mohdsabahat** [Merubokkusu/Discord-S.C.U.M#331]
When i click on a button using my userbot it shows this "Invalid Form Body" error!

I think this is due to the recent update in discord.
I also was getting the same error in discord android app until i updated it..

![IMG_20220216_125349](https://user-images.githubusercontent.com/65245619/154215952-8508fd7a-4b9b-421b-b6c1-ac361fd24620.jpg)

**Comment by ldapuser** [comment]
> When i click on a button using my userbot it shows this "Invalid Form Body" error!
> 
> I think this is due to the recent update in discord. I also was getting the same error in discord android app until i updated it..
> 
> ![IMG_20220216_125349](https://user-images.githubusercontent.com/65245619/154215952-8508fd7a-4b9b-421b-b6c1-ac361fd24620.jpg)

Hi, i updated body dict in button.py with required parametr "session_id":
`body = {
			"type": 3,
			"nonce": nonce,
			"guild_id": guildID,
			"channel_id": channelID,
			"message_flags": messageFlags,
			"message_id": messageID,
			"application_id": applicationID,
			"data": data,
			"session_id": self.s.cookies.get('__dcfduid'),
		}`

**Comment by BadozChopra** [comment]
Make the following changes, Keep in mind for this to work you'll need an active gateway connection.
```py
    #  ./discum/discum.py - Client.click
    def click(self, applicationID, channelID, messageID, messageFlags, guildID=None, nonce="calculate", data={}):
        return imports.Buttons(self.discord, self.s, self.log).click(applicationID, channelID, messageID, messageFlags, guildID, nonce, data, self.gateway.session_id)

    #  ./discum/interactions/buttons.py - Buttons.click
    def click(self, applicationID, channelID, messageID, messageFlags, guildID, nonce, data, sessionId):
        url = self.discord+"interactions"
        if nonce == "calculate":
            from ..utils.nonce import calculateNonce
            nonce = calculateNonce()
        else:
            nonce = str(nonce)
        body = {
            "type": 3,
            "nonce": nonce,
            "guild_id": guildID,
            "channel_id": channelID,
            "message_flags": messageFlags,
            "message_id": messageID,
            "application_id": applicationID,
            "data": data,
            "session_id": sessionId
        }
        if guildID == None:
            body.pop("guild_id")
        return Wrapper.sendRequest(self.s, 'post', url, body, log=self.log)
```

**Comment by dolfies** [comment]
You can also use a randomly generated session id.

**Comment by cojored** [comment]
> You can also use a randomly generated session id.

That is discouraged as it being invalid could cause discord to ban the bot as it would be apparent that it is not a legitimate user

**Comment by dolfies** [comment]
> > You can also use a randomly generated session id.
> 
> That is discouraged as it being invalid could cause discord to ban the bot as it would be apparent that it is not a legitimate user

They don't check them currently, so an invalid one is fine if you don't have a gateway connection. Just generate a believable one.

```py
def _generate_session_id() -> str:
    return ''.join(random.choices(string.ascii_letters + string.digits, k=16))
```

**Comment by definitelynotanalt** [comment]
> Make the following changes, Keep in mind for this to work you'll need an active gateway connection.
> 
> ```python
>     #  ./discum/discum.py - Client.click
>     def click(self, applicationID, channelID, messageID, messageFlags, guildID=None, nonce="calculate", data={}):
>         return imports.Buttons(self.discord, self.s, self.log).click(applicationID, channelID, messageID, messageFlags, guildID, nonce, data, self.gateway.session_id)
> 
>     #  ./discum/interactions/buttons.py - Buttons.click
>     def click(self, applicationID, channelID, messageID, messageFlags, guildID, nonce, data, sessionId):
>         url = self.discord+"interactions"
>         if nonce == "calculate":
>             from ..utils.nonce import calculateNonce
>             nonce = calculateNonce()
>         else:
>             nonce = str(nonce)
>         body = {
>             "type": 3,
>             "nonce": nonce,
>             "guild_id": guildID,
>             "channel_id": channelID,
>             "message_flags": messageFlags,
>             "message_id": messageID,
>             "application_id": applicationID,
>             "data": data,
>             "session_id": sessionId
>         }
>         if guildID == None:
>             body.pop("guild_id")
>         return Wrapper.sendRequest(self.s, 'post', url, body, log=self.log)
> ```

@BadozChopra can you make a pull request with these changes? This should 100% be part of the main discum library, it's a much needed bugfix. Thanks.
