### ISSUE TITLE
send_message returns 401 Unathorized

### ISSUE THREAD

**Issue by DadMych** [Merubokkusu/Discord-S.C.U.M#338]
![image](https://user-images.githubusercontent.com/60585194/155359519-d99267ea-4863-470b-aaa8-cf64af94074f.png)
This code returns 401 Unathorized
Logs:
 [+] (<discum.start.login.Login->getXFingerprint) Get -> https://discord.com/api/v9/experiments
 [+] (<discum.start.login.Login->getXFingerprint) Response <- b'{"fingerprint": "946076281647296572.NtrLJGxVuksddA5WFZu_WtQuPqM", "assignments": [[70411085, 0, 1, -1, 0], [1865079242, 0, 1, -1, 0], [16416918, 0, 1, -1, 0], [3816091942, 3, 2, -1, 0], [4130837190, 0, 10, -1, 0], [1578940118, 1, 1, -1, 0], [1571676964, 0, 1, -1, 2], [3640172371, 0, 2, -1, 2], [98883956, 1, 1, -1, 0], [4007615411, 0, 1, -1, 0], [852550504, 3, 1, -1, 0], [1127795596, 1, 1, -1, 0], [4168223991, 0, 1, -1, 0], [327482016, 0, 1, -1, 2], [3458098201, 7, 1, -1, 0], [478613943, 2, 1, -1, 1], [2099185390, 0, 1, -1, 0], [1202202685, 0, 1, -1, 0], [2122174751, 0, 1, -1, 0], [820624960, 0, 1, -1, 0], [2599708267, 0, 1, -1, 0], [613180822, 1, 1, -1, 0], [2885186814, 0, 1, -1, 0], [1054317075, 0, 1, -1, 3], [1739278764, 0, 2, -1, 0], [3721841948, 0, 1, -1, 0], [415992370, 1, 1, -1, 0], [1365487849, 6, 1, -1, 0], [955229746, 0, 1, -1, 0], [3128009767, 0, 10, -1, 0], [2368314642, 1, 1, -1, 0], [441885003, 0, 1, -1, 0], [3433971238, 0, 1, -1, 2], [1038765354, 3, 1, -1, 0], [3649806352, 1, 1, -1, 0], [2973729510, 2, 1, -1, 0], [2571931329, 1, 6, -1, 0], [3884442008, 0, 1, -1, 0], [978673395, 1, 1, -1, 0], [1260103069, 0, 1, -1, 0], [2003494159, 1, 1, -1, 0], [2458926251, 1, 6, -1, 2], [4027800, 1, 6, -1, 3], [51193042, 0, 1, -1, 0], [2063302207, 1, 1, -1, 0], [2634540382, 3, 1, -1, 0], [427713714, 0, 1, -1, 0], [3388129398, 0, 1, -1, 0], [3316720711, 0, 1, -1, 0], [156590431, 0, 1, -1, 2], [1126477623, 0, 1, -1, 0], [2617218444, 4, 1, -1, 2], [3615263239, 0, 1, -1, 0], [414823706, 0, 1, -1, 0], [3035674767, 0, 1, -1, 0], [261678880, 0, 1, -1, 0], [1758928808, 2, 1, -1, 0], [144783748, 0, 1, -1, 0], [2898830675, 0, 1, -1, 0], [2311413706, 0, 1, -1, 0], [1304635016, 0, 1, -1, 0], [2031154483, 0, 1, -1, 0], [3840356350, 4, 1, -1, 0], [1609782151, 0, 0, -1, 2], [1047093347, 0, 1, -1, 2], [3354177721, 0, 1, -1, 0], [3643362751, 0, 1, -1, 0], [698017395, 0, 1, -1, 0], [902020832, 3, 3, -1, 1], [1503481915, 0, 1, -1, 2], [3346844407, 0, 1, -1, 0], [3753034466, 1, 2, -1, 0], [881221695, 1, 1, -1, 0], [105505141, 1, 1, -1, 1], [3749399219, 0, 1, -1, 0], [55060776, 1, 2, -1, 0], [3921541483, 2, 1, -1, 0], [3125584553, 1, 1, -1, 0], [219203323, 1, 1, -1, 0], [2854861606, 0, 1, -1, 1], [203190011, 0, 1, -1, 0], [2416791266, 1, 1, -1, 0], [1740882580, 1, 1, -1, 0], [3526033165, 0, 1, -1, 0], [3699939463, 0, 1, -1, 2], [1913882179, 0, 1, -1, 2], [3884403666, 1, 1, -1, 0], [1041569008, 0, 1, -1, 0], [949804751, 3, 1, -1, 0], [2365882538, 1, 1, -1, 0], [2780619238, 1, 2, -1, 0], [2839301427, 1, 1, -1, 0], [2740541143, 1, 1, -1, 0], [1567199723, 0, 1, -1, 0], [2237617796, 0, 1, -1, 0], [2804024497, 0, 1, -1, 2], [2481496956, 0, 1, -1, 0], [1305004983, 0, 1, -1, 0], [4196771574, 6, 6, -1, 0], [3121542871, 1, 1, -1, 0], [934741861, 2, 1, -1, 1], [2639499196, 3, 1, -1, 1], [1926403380, 0, 1, -1, 0], [3668799047, 1, 1, -1, 0], [1751210224, 0, 1, -1, 0], [1175582167, 1, 1, -1, 0], [2012365622, 0, 2, -1, 0], [3615787841, 0, 1, -1, 0], [2386280948, 3, 1, -1, 0], [1369422507, 0, 1, -1, 0], [3067177633, 0, 1, -1, 0], [1515594840, 0, 0, -1, 0], [4257117014, 1, 1, -1, 0], [2191591221, 0, 1, -1, 0], [2486591316, 0, 1, -1, 1], [1003602213, 0, 1, -1, 0], [1860870966, 0, 1, -1, 0], [613690816, 2, 1, -1, 0], [1184450869, 0, 0, -1, 0], [754424255, 0, 1, -1, 0], [282861292, 0, 0, -1, 0], [2950595281, 2, 1, -1, 0], [4263969313, 2, 1, -1, 2], [3380195506, 0, 1, -1, 0], [1802750862, 0, 1, -1, 0], [2693826169, 0, 1, -1, 0], [68859362, 1, 1, -1, 0], [2496945544, 0, 0, -1, 0], [3662016164, 3, 2, -1, 0], [2486607747, 0, 1, -1, 0], [604497254, 0, 0, -1, 0], [2736193736, 0, 1, -1, 0], [1138665623, 0, 1, -1, 0], [3542498455, 0, 1, -1, 0], [723256323, 0, 1, -1, 0], [3441019492, 0, 1, -1, 0], [2393539652, 1, 1, -1, 0], [3866818837, 0, 1, -1, 0], [334012295, 0, 1, -1, 0], [1748842958, 1, 1, -1, 0], [1630149773, 1, 3, -1, 0], [3047034364, 0, 2, -1, 0]]}'
 [+] (<discum.messages.messages.Messages->sendMessage) Post -> https://discord.com/api/v9/channels/494094746176847899/messages
 [+] (<discum.messages.messages.Messages->sendMessage) {"content": "Hello :)", "tts": false, "nonce": "946076282519552000"}
 [+] (<discum.messages.messages.Messages->sendMessage) Response <- b'{"message": "401: Unauthorized", "code": 0}'

**Comment by timmsGithub** [comment]
Login with the token and see if you can write a message in the chat with the id.

Be sure to be in the guild, and can write in the channel!
