### ISSUE TITLE
messages with emojis are completely ignored.

### ISSUE THREAD

**Issue by Errorcrafter** [Merubokkusu/Discord-S.C.U.M#339]
all messages containing emojis, both default and custom, get ignored by discum. messages with other high unicode code points (above `\u100`) are also ignored.

**Comment by Errorcrafter** [comment]
upd: i was wrong, messages containing unicode code points 256 and above break completely. it seems to be some kind of encoding error? but i'm not well-versed enough in this library to figure out why thiswould be so

**Comment by BalaM314** [comment]
Update: this seems to only happen when logging to file is enabled. It works fine otherwise.

**Comment by BalaM314** [comment]
I've found the issue.
![image](https://user-images.githubusercontent.com/71201189/155926369-bd0a58e0-3767-473f-93ef-5df320cc4ad4.png)
It appears errors are being thrown in Logger.log when it tries to write a non-utf8 character, but instead of throwing the error it just silently fails. ✨ python ✨
