### ISSUE TITLE
Slash Rolling has stopped working

### ISSUE THREAD

**Issue by vivinano** [Merubokkusu/Discord-S.C.U.M#345]
Title

**Comment by shsagnik** [comment]
vivano I saw that in your repo you have somehow found a temporary fix for the time being
can you share it here please with a bit of explanation

**Comment by shsagnik** [comment]
@vivinano  Please help

**Comment by vivinano** [comment]
basically after updating to the newest version of repo (V1.4) I saw that there were changes in the slash object and seeing that the .get() of the class was only getting the 1st element 

so through trail and error use and figuring out the type of elements I was able to eventually get to the `list` of `Dicts` so I decided to for loop through each element comparing if it the command I wanted and then send that index into my slash trigger command

Definitely not the best implementation of a fix but for my case it works

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/156933557-586f93d3-945e-46ee-8f36-86459cdfdf4c.png)

It is technically somewhat like how the .get( ) commands works currently which iterates though each one looking at the name

**Comment by shsagnik** [comment]
Thanks a lot for your input, I followed your repo and have got it to work for my case as well

**Comment by vivinano** [comment]
@shsagnik 

https://github.com/Merubokkusu/Discord-S.C.U.M/pull/346

so I had a little free time to look at the source code and it seems like the `self._isAtOuterLvl(c)` was causing a issue after taking it out the get command was working like it use to for me

**Comment by vivinano** [comment]
As my changes have been merged this should be resolved
