### ISSUE TITLE
Failure determining discord build number

### ISSUE THREAD

**Issue by trippy22** [Merubokkusu/Discord-S.C.U.M#348]
I've been seeing this lately when initializing, although it seems like things still work. Is this cause for any concern?

```
Retrieving Discord's build number...
Could not retrieve discord build number.
invalid literal for int() with base 10: 'ull!=='
```

I also tried upgrading the library with `python -m pip install --user --upgrade git+https://github.com/Merubokkusu/Discord-S.C.U.M.git#egg=discum` before posting this issue.

**Comment by OrionCodeDev** [comment]
On latest version it's working fine. Try download it manually. Issue can be closed.
