### ISSUE TITLE
Can't seem to interact with buttons in discord

### ISSUE THREAD

**Issue by GamerStudio3YT** [Merubokkusu/Discord-S.C.U.M#372]
I've read the documentation. I want to scan all messages in a specific channel and then detect and click buttons but I couldn't figure out how to do it. Any help is appreciated!

**Comment by vivinano** [comment]
![image](https://user-images.githubusercontent.com/33008397/168623389-f7d5430e-d667-448b-92c9-762f707f8586.png)

This how I did mine

**Comment by GamerStudio3YT** [comment]
Thanks
