### ISSUE TITLE
Cannot figure out how to invoke a bot's slash command using the selfbot

### ISSUE THREAD

**Issue by MrParniple** [Merubokkusu/Discord-S.C.U.M#404]
I want to get my selfbot to trigger the MidJourney bot's /imagine command.

I can't figure out how to invoke a slash command. I am trying to use the "/imagine" command with the MidJourney bot (ID below). I am rather novice, but I cannot figure out what "saved", "queues", and "create" refer to. Are they just example commands? Are we supposed to replace those strings with the commands we know the bot has? For Inputs, do we replace "name" also? If I typed it normally in discord, the command looks like "/imagine  prompt: example content of my prompt". 

Is this right?
`data = s.get(['imagine'], inputs={'prompt':'example content of my prompt'})`
or
`data = s.get(['imagine'], inputs={'name':'example content of my prompt'})`

None of it is doing anything in Discord. The only thing I have working is sending a normal message. I can't get the Selfbot to trigger the MidJourney bot's /imagine command.

`import discum
bot = discum.Client(token='myTokenID')

#The following example is the recommended way for triggering slash commands in a guild.
from discum.utils.slash import SlashCommander

def slashCommandTest(resp, guildID, channelID, botID):
	if resp.event.ready_supplemental:
		bot.gateway.request.searchSlashCommands(guildID, limit=10, query="saved") #query slash cmds
	if resp.event.guild_application_commands_updated:
		bot.gateway.removeCommand(slashCommandTest) #because 2 guild_app_cmd_update events are received...idk ask discord why
		slashCmds = resp.parsed.auto()['application_commands'] #get the slash cmds
		s = SlashCommander(slashCmds, application_id=botID) #for easy slash cmd data creation
		# data = s.get(['saved', 'queues', 'create'], inputs={'name':'test'})
		data = s.get(['imagine'], inputs={'name':'example content of my prompt'})
		bot.triggerSlashCommand(botID, channelID=channelID, guildID=guildID, data=data) #and send it off
		#bot.gateway.close() #optional. It's better to remove this line actually.
`		print('command sent')`
		
guildID = "myguildID"
channelID = "mychannelID"
botID = "936929561302675456" #midjourney bot IDs
bot.gateway.command(
	{
		"function": slashCommandTest,
		"params": {"guildID": guildID, "channelID": channelID, "botID": botID},
	}
)
bot.gateway.run()`

**Comment by MrParniple** [comment]
Nevermind, I figured it out. I needed to change 

`bot.gateway.request.searchSlashCommands(guildID, limit=10, query="saved") #query slash cmds`
to
`bot.gateway.request.searchSlashCommands(guildID, limit=10, query="imagine") #query slash cmds`

**Comment by Varin6** [comment]
@MrParniple I'm working on this same thing right now (Midjourney). Have you managed to get this to work in a way that you can trigger the /imagine in a loop or by calling a custom command ?

**Comment by MrParniple** [comment]
@Varin6 Yeah, through some hackery. I use an app called Airtable to store a list of my commands. Then I use an app called Zapier to lookout for info in Airtable that is meant to be posted at a certain time, to grab it at that time, and post it in a private discord server (user Zapier's built in integration) with my account, Midjourney, and the Zapier bot. I then wrote a script based on one of the example scripts here to listen to messages posted from the bot, and to resend the message as part of a prompt with the "imagine" slash command after waiting a random interval of seconds. I then have it run all night on relax mode and create images for me based on what I wrote in Airtable, which I check in the morning and put on fast mode to make upscales of the ones I like.

**Comment by MrParniple** [comment]
Yeah, through some hackery. I use an app called Airtable to store a list of my commands. Then I use an app called Zapier to lookout for info in Airtable that is meant to be posted at a certain time, to grab it at that time, and post it in a private server with my account, Midjourney, and the Zapier bot. I then wrote a script based on one of the example scripts here to listen to messages posted from the bot, and to resend the message as part of a prompt with the "imagine" slash command after waiting a random interval of seconds. I then have it run all night on relax mode and create images for me based on what I wrote in Airtable, which I check in the morning and put on fast mode to make upscales of the ones I like.

**Comment by Varin6** [comment]
@MrParniple Thanks for the answer, any chance you could share the code if that's opensource? I've managed to get self bot set up in a way that it checks all incoming messages on a private channel, and if the message starts with `--imagine` it then treats the rest of the message as a prompt and calls `/imagine` in relaxed mode on a MJ bot. I basically wanted a channel where I can share my subscription with my partner and my sister, rather than them asking me all the time to do it for them :) 

Next is basically what you have done - I need to build a function where I can loop over prompts and automate generation. Thinking about plugging it to RabbitMQ. My discord in case: Varin#5089
