### ISSUE TITLE
bot.gateway.run issue

### ISSUE THREAD

**Issue by ryouzue** [Merubokkusu/Discord-S.C.U.M#405]
Using the old src of a bot and the latest version of Discum. I tried to find solutions for the matter where the bot never runs, it remains stuck after executing `py main.py` (the bot file) If I attempt to set auto_reconnect to False, it exits within a second orso.

![image](https://user-images.githubusercontent.com/74881934/184500214-939190c7-30a5-4661-bef8-258927ec7b7d.png)

[Source of the bot I'm running](https://github.com/vivinano/MudaeAutoBot/blob/main/MudaeAutoBot.py)

**Comment by ahihiyou20** [comment]
> 

Maybe your token is invalid. Discum doesn't return any exception if only half of your token is invalid
Discord stores 2 thing in your token, your user ID (encoded with base64) and your authorization code. Discum only returns exeption if your ID is invalid.

**Comment by ryouzue** [comment]
> Maybe your token is invalid. Discum doesn't return any exception if only half of your token is invalid Discord stores 2 thing in your token, your user ID (encoded with base64) and your authorization code. Discum only returns exeption if your ID is invalid.

Uhh I don't believe that 'cause I made a new token for the bot couple of times before I open this issue

**Comment by NeutronBlast** [comment]
Did you set logging to false? I would like to see what the logs say

**Comment by ryouzue** [comment]
> Did you set logging to false? I would like to see what the logs say

https://cdn.fractune.dev/oni/2xcn82.mp4

**Comment by NeutronBlast** [comment]
Did you try to login with the same token manually? From the output it looks like the token expired

**Comment by ahihiyou20** [comment]
> > Did you set logging to false? I would like to see what the logs say
> 
> https://cdn.fractune.dev/oni/2xcn82.mp4

Are you trying to run your selfbot with a bot account? 
#262

**Comment by Fractune** [comment]
> Are you trying to run your selfbot with a bot account? #262

I thought it was obvious when I made this ticket, I'm using a bot account

**Comment by ryouzue** [comment]
> Are you trying to run your selfbot with a bot account? #262

I thought it was obvious when I made this ticket, I'm using a bot account

> Did you try to login with the same token manually? From the output it looks like the token expired

Every time I reset token, that's the error I get. I made a new app agan & same result

**Comment by ahihiyou20** [comment]
> > Are you trying to run your selfbot with a bot account? #262
> 
> I thought it was obvious when I made this ticket, I'm using a bot account
> 
> > Did you try to login with the same token manually? From the output it looks like the token expired
> 
> Every time I reset token, that's the error I get. I made a new app agan & same result

Dude discum is a package for **Selfbot**, which mean you need to use an user account, not bot account. And also the src you're using is for selfbot, not bot. Look for a tutorial on YouTube about getting user account's token.

**Comment by ryouzue** [comment]
> Dude discum is a package for **Selfbot**, which mean you need to use an user account, not bot account. And also the src you're using is for selfbot, not bot. Look for a tutorial on YouTube about getting user account's token.

I don't need a tutorial however the src I'm using also mentions that it's for a bot's account (not DISCUM though) but thanks for clarifying that out.

**Comment by ahihiyou20** [comment]
> 
> > Dude discum is a package for **Selfbot**, which mean you need to use an user account, not bot account. And also the src you're using is for selfbot, not bot. Look for a tutorial on YouTube about getting user account's token.
> 
> I don't need a tutorial however the src I'm using also mentions that it's for a bot's account (not DISCUM though) but thanks for clarifying that out.

In the desc of the bot you're using, they said you need an **user token** which mean that's a selfbot (And discum can't even run on bot account)
