### ISSUE TITLE
Send 1 message but print(m['content']) out is 3 ?

### ISSUE THREAD

**Issue by Naru2203** [Merubokkusu/Discord-S.C.U.M#414]
![image](https://user-images.githubusercontent.com/101044276/188261888-8f0bbd27-83b5-4312-b3b2-458224828c02.png)
![image](https://user-images.githubusercontent.com/101044276/188261964-bf29ceea-7542-4e9c-94f0-fcbc6b855180.png)

-.- Can anyone help with this issue?

**Comment by IonescoHODL** [comment]
I think I have a similar issue. 
I wait a message and when it's received, the selfbot should use SlashCommander to call a bot. 
But sometimes, the call is duplicated (I would say, 1 time on 10 or 15). 

Here is the concerned part of the code. It should send something like /admin-chips add @user 1000
and sometimes, it sends 2 in a row 
```

    ### RETRIEVES THE MESSAGE ###
        message = resp.parsed.auto()
        content = message['content']

        ### HANDLES /admin-chips add (@user) (quantity)
        if content.startswith('!chips'):
            arguments['mention'] = content[content.find('<')+2:content.find('>')].replace('!', '')
            arguments['quantity'] = content[6:content.find('<')].strip()
            arguments['admin-chips'] = 'add'
            # print("mention :",arguments['mention']+"\n", "quantity :", arguments['quantity'])
            bot.gateway.request.searchSlashCommands(guildID, limit=10, query='admin-chips')
```
