### ISSUE TITLE
Embedded messages as a user? Or api broken?

### ISSUE THREAD

**Issue by Treebeardz** [Merubokkusu/Discord-S.C.U.M#420]
When using the embedded example in the documentation nothing happens? Can embedded messages not be sent as user or with a user token? Can only bots can send them? Has the API changed?

For example this from the documentation... This does not work.

from discum.utils.embed import Embedder
embed = Embedder()
embed.title("This is a test")
embed.image('https://cdn.dribbble.com/users/189524/screenshots/2105870/04-example_800x600_v4.gif')
embed.fields('Hello!',':yum:')
embed.fields(':smile:','Testing :)')
embed.author('Tester')
embed.color(15158332) # Colors must be integer
bot.sendMessage("383006063751856129","", embed=embed.read())

**Comment by NeutronBlast** [comment]
Pretty sure that's not possible anymore due to a Discord update

**Comment by OttoGrotto** [comment]
Not possible anymore due to an API update, quite a while back too I think, you'll get an error when trying the same in js counterparts
