### ISSUE TITLE
Is it possible to enter audio channels?

### ISSUE THREAD

**Issue by tanersb** [Merubokkusu/Discord-S.C.U.M#421]
Is it possible to enter an audio channel in any way?

**Comment by NeutronBlast** [comment]
Yes. In gateway actions there are functions to join and leave voice channels

[https://github.com/Merubokkusu/Discord-S.C.U.M/blob/master/docs/using/Gateway_Actions.md](url)

**Comment by tanersb** [comment]
yeah its work thanks @NeutronBlast .  How can I change the microphone and camera settings after entering the voice channel? {mute=True,deaf=True,video=True} or {mute=False ,deaf=False ,video=False}

**Comment by NeutronBlast** [comment]
If I recall correctly, muted / deafen settings don't trigger API requests, so Discum wouldn't handle that, those settings are stored in localStorage in MediaEngineStore

**Comment by tanersb** [comment]
@NeutronBlast hm i understand. thanks for everything.
