### ISSUE TITLE
.

### ISSUE THREAD

**Issue by WarningDarbe** [Merubokkusu/Discord-S.C.U.M#447]

**Comment by behind24proxies** [comment]
> When I use it for a long time, sometimes the account cannot receive messages, what should I do?

Make a new acount, alternate the usage
🤏🧠

**Comment by WarningDarbe** [comment]
> > When I use it for a long time, sometimes the account cannot receive messages, what should I do?
> 
> Make a new acount, alternate the usage pinching_handbrain

i dont understant. why i should make a new account?
