### ISSUE TITLE
KeyError: 'guilds'

### ISSUE THREAD

**Issue by Mlmcore** [Merubokkusu/Discord-S.C.U.M#452]
So everything works just fine as long as I'm not on some specific servers . I'm guessing they are using some new channels ?? 
One of those servers is  https://discordservers.com/server/127124571382874112 (https://discord.gg/discord-tabletop-127124571382874112)
Any fix for this (also it works just fine if I downgrade to 1.1.0 but I'm having other unrelated issues there ..

Please Help.

![image](https://user-images.githubusercontent.com/58560273/216204496-8ee6225e-2986-4fb8-a80d-142df201c7d8.png)

**Comment by Mlmcore** [comment]
https://github.com/Merubokkusu/Discord-S.C.U.M/issues/432#issuecomment-1360419048
nvm I love you

**Comment by LightCannon** [comment]
Sorry, what was the solution? Reinstalling seems not solving it.
What did u do to solve it exactly?
