### ISSUE TITLE
Sus discum activity when downloaded by using "pip install -r requirements"

### ISSUE THREAD

**Issue by racontre** [Merubokkusu/Discord-S.C.U.M#462]
I don't know what it is, but:
Apparently it's trying to send messages or something when all I'm doing in code is parsing members of a guild and getting their profile after that?
it has that keyError ["guilds"] that people have been complaining about, too
and it keeps executing forever

If I install directly from github I have none of these issues. Could the library be hijacked somehow?

Unexpected behavior after installing requirements:
![image](https://user-images.githubusercontent.com/7081938/225612208-e18a5941-22a0-4273-a78e-fbfe950f0aa0.png)

weird heartbeat ready stage, I'm not sure if it's in both versions, I don't think so
outputs a bunch of data about the selfbot
<img width="662" alt="Screenshot_143" src="https://user-images.githubusercontent.com/7081938/225613527-afca467e-4626-41a9-84f4-b09801d0a046.png">

How it's supposed to look basically:
![image](https://user-images.githubusercontent.com/7081938/225615111-c6a7295f-f1b0-4835-b5a1-9e7b219731f9.png)

**Comment by racontre** [comment]
It kind of seems to appear at random now that I look at it, but reinstalling definitely helped for some reason...

**Comment by AreYouMehmetEfeisModder** [comment]
same error
