### ISSUE TITLE
commands & events

### ISSUE THREAD

**Issue by FeelsBadMan1** [Merubokkusu/Discord-S.C.U.M#49]
Hello,
If i create some commands using @bot.gateway.command
The bot response to all messages.
Is there a way to create commands and define a prefix into a variable that will be need to be used in order to use commands?
____________
arandomnewaccount:
yep. The only thing needed to implement a prefix is to check the beginning of a message string. So, a simple example would be:
```python
@bot.gateway.command
def test(resp):
	if resp.event.message:
		m = resp.parsed.auto()
		if m['content'].startswith('!'):
			cmd = m['content'][1:]
			if cmd == "reply":
				bot.reply(m['channel_id'], m['id'], 'hi')
```
What the code above does is it checks if every message starts with the prefix ! and if it does, checks if the command is "reply". If it is, it replies to the message with "hi".

If we want to pass in the prefix as a parameter, we can do that too:
```python
def test(resp, prefix):
	if resp.event.message:
		m = resp.parsed.auto()
		if m['content'].startswith(prefix):
			cmd = m['content'][1:]
			if cmd == "reply":
				bot.reply(m['channel_id'], m['id'], 'hi')

prefix = "!"
bot.gateway.command({"function": test, "params": {"prefix": prefix}})
```
Similarly, we can also pass in the command/function as a parameter:
```python
def prefixHandler(resp, prefix, function):
	if resp.event.message:
		m = resp.parsed.auto()
		if m['content'].startswith(prefix):
			cmd = m['content'][1:]
			function(cmd, m)

def reply(cmd, m):
	if cmd == "reply":
		bot.reply(m['channel_id'], m['id'], 'hi')

prefix = "!"
bot.gateway.command({"function": prefixHandler, "params": {"prefix": prefix, "function": reply}})
```

**Comment by FeelsBadMan1** [comment]
is it possible to do it like discord.py with @bot.command and definie prefix as variable etc?

**Comment by FeelsBadMan1** [comment]
also wihile using the last code you sent i get this errorlog:

```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000027C0E9739D0>>
Traceback (most recent call last):
  File "D:\my_python_projects\Servercopy - Discordbot\venv\lib\site-packages\discum\gateway\gateway.py", line 249, in _response_loop
    func(resp)
TypeError: prefixHandler() missing 2 required positional arguments: 'prefix' and 'function'
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000027C0E9739D0>>
Traceback (most recent call last):
  File "D:\my_python_projects\Servercopy - Discordbot\venv\lib\site-packages\discum\gateway\gateway.py", line 249, in _response_loop
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000027C0E9739D0>>
Traceback (most recent call last):
  File "D:\my_python_projects\Servercopy - Discordbot\venv\lib\site-packages\discum\gateway\gateway.py", line 249, in _response_loop
    func(resp)
TypeError: prefixHandler() missing 2 required positional arguments: 'prefix' and 'function'
    func(resp)
TypeError: prefixHandler() missing 2 required positional arguments: 'prefix' and 'function'
```
_______________________
arandomnewaccount:
huh, I tried it on my end and it worked fine. Also, in the 2nd to last example and in the last example, you can see prefix defined as a variable. I haven't figured out how to nicely pass variables into @bot.gateway.command...prob something I'd have to do with functools. 

Also, I see in your error log that discum's running func(resp) instead of function(resp, **params), which indicates that you're using ```@bot.gateway.command``` instead of the 
```python
bot.gateway.command({"function": prefixHandler, "params": {"prefix": prefix, "function": reply}})
``` 
line at the end.

**Comment by tchavei** [comment]
Maybe this would be easier:

```
trigger='!'

if message['content'].startswith(f'{trigger}reply'):
     ...
     your code
     ...
```
______________
arandomnewaccount:
yea that's good too. F strings are nice; the reason I don't use them in discum's code is because they're not supported in python versions below 3.6.

edit: closing this as answered.

**Comment by FuckingToaster** [comment]
> Maybe this would be easier:
> 
> ```
> trigger='!'
> 
> if message['content'].startswith(f'{trigger}reply'):
>      ...
>      your code
>      ...
> ```
> 
> arandomnewaccount: yea that's good too. F strings are nice; the reason I don't use them in discum's code is because they're not supported in python versions below 3.6.
> 
> edit: closing this as answered.

seems easier however is there a way to check the exact prefix and not only startwith? e.g
i want a command called !test now with the example the bot would response even on any arguments passed to the command !test these are arguments

now what it shoud do, only response to !test not to !test xd lol

**Comment by tchavei** [comment]
Use f"{trigger}test "

With the blank space you're assuring it's the correct command and not
!testsomething. If you don't want to allow parameters at all, do a simple
match instead of starts with.

A terça, 9/11/2021, 14:47, FuckingToaster ***@***.***>
escreveu:
