### ISSUE TITLE
wonder how to dm someone with a mutual server

### ISSUE THREAD

**Issue by ghost** [Merubokkusu/Discord-S.C.U.M#52]
arandomnewaccount:
As stated in the readme, bot.createDM, bot.requestFriend, and bot.joinGuild are risky to use. I highly recommend using a browser automator (like selenium or pyppeteer) for these 3 actions.

edit: closing this as it's pretty much a duplicate of #41

**Comment by captain-majid** [comment]
Any hints for using selenium or pyppeteer as a mass dm tool ?
