### ISSUE TITLE
sendMessage() function

### ISSUE THREAD

**Issue by An9el0baby** [Merubokkusu/Discord-S.C.U.M#72]
Hi, 
i wrote a code like 
bot.sendMessage(f"{channel1}",content1)
bot.sendMessage(f"{channel2}",content2)
but only the first message send. The second one didn't work.
Is there anything wrong with my code?

**Comment by An9el0baby** [comment]
I think I worked it out by adding a time.sleep(1)

**Comment by An9el0baby** [comment]
How do I get user name by knowing user's discord id?

**Comment by ghost** [comment]
> How do I get user name by knowing user's discord id?

check documention

**Comment by An9el0baby** [comment]
> > How do I get user name by knowing user's discord id?
> 
> check documention

Thanks! I figure it out.
