### ISSUE TITLE
ALL HAI ANARCHY

### ISSUE THREAD

**Issue by The-Discord-Programs-Guy** [Merubokkusu/Discord-S.C.U.M#9]
ANARCHY
ANARCHY

**Comment by deadly** [comment]
all hail discum

**Comment by Merubokkusu** [comment]
Not sure the point of this.

If this is an attempt at a “raid”, discum is a python api while anarchy is C#. 

Different libraries exist.

**Comment by The-Discord-Programs-Guy** [comment]
nah its a joke :)
