### ISSUE TITLE
Websocket closes after a few hours of running

### ISSUE THREAD

**Issue by ExtremSnek** [Merubokkusu/Discord-S.C.U.M#96]
Having the same issue as [https://github.com/Merubokkusu/Discord-S.C.U.M/issues/89](this issue). My selfbot runs well for a while, then the websocket closes after some amount of time (maybe after couple hours of it running?). If it helps I run this on repl.it as a free discord bot hoster and that might limit the ram or speed of the process. Please answer if you know the solution.
__________
arandomnewaccount:
currently a bit busy - I believe your issue has to do with repl rather than discum. 
Try http://pythonanywhere.com/ or https://www.heroku.com/.

**Comment by sterling-tenn** [comment]
Same issue, I kept the log open to find the issue and I noticed:
`Access denied | discord.com used Cloudflare to restrict access
The owner of this website (discord.com) has banned your access based on your browser's signature`
in the log file.

**Comment by ExtremSnek** [comment]
> arandomnewaccount:
> currently a bit busy - I believe your issue has to do with repl rather than discum.
> Try http://pythonanywhere.com/ or https://www.heroku.com/.

I have successfully moved the program to heroku and will notify if the websocket closing still happens, thanks. I will also be using my other bots on this because it seems really good haha.

**Comment by ExtremSnek** [comment]
After moving to heroku, I let the bot run and it seems to have shut off again. I restarted it and after a few hours, which seemed to be less time than on repl.it, the same error message: "Websocket connection is already closed" appears.

**Comment by sterling-tenn** [comment]
> arandomnewaccount:
> see the [FAQ on the readme](https://github.com/Merubokkusu/Discord-S.C.U.M#faq). Just change your client's user agent.

Where do in the documentation does it reference how to change the user agent?

**Comment by ExtremSnek** [comment]
I think I've fixed it, so for anyone scrolling through this who has this issue, check your requirements and make sure the websocket client is version 0.59.0, because for some reason the websocket doesn't close.

**Comment by ExtremSnek** [comment]
In addiction to switch to version websocket_client==0.59.0 I also changed my discum version to 1.3 in my requirements
